### ISSUE TITLE
Using rollup-plugin-external-assets results in empty source map files

### ISSUE THREAD

**Issue by rickharris** [recursive-beast/rollup-plugin-external-assets#75]
I put a small test case together to show the issue: https://github.com/rickharris/rollup-external-assets-sourcemap-test

The repo has two source files `without-assets.js` and `with-assets.js`, the latter imports a png. The two files have two separate rollup configs, that are identical except the one for `with-assets.js` uses `rollup-plugin-external-assets` to copy & mark the asset it imports as external.

When built, the file `without-assets.js.map` file has all the information you'd expect in a source map:

```map
{"version":3,"file":"without-assets.js","sources":["../without-assets.js"],"sourcesContent":["import { log } from \"console\";\n\nlog(\"HELLO\");\n"],"names":[],"mappings":";;AAEA,GAAG,CAAC,OAAO,CAAC"}
```

For the file that is built with `rollup-plugin-external-assets` in the plugins list, the source map file is still present but lacks any actual mapping information:

```map
{"version":3,"file":"with-assets.js","sources":[],"sourcesContent":[],"names":[],"mappings":""}
```

Hope this helps!

**Comment by recursive-beast** [comment]
@rickharris Fixed! Thank you for pointing this out.
